services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
        volumes:
            - ./frontend:/app
            - /app/node_modules # Do not let host modules overwrite container modules
            - /app/.svelte-kit # Keep internal build artifacts in the container
        depends_on:
            - backend
        networks:
            - portfolio-net

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile.dev
        volumes:
            - ./backend:/app
            - /app/.venv
        networks:
            - portfolio-net

    caddy:
        image: caddy:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - caddy_data:/data
            - caddy_config:/config
        depends_on:
            - frontend
        networks:
            - portfolio-net

networks:
    portfolio-net:
        driver: bridge

volumes:
    caddy_data:
    caddy_config:
