services:
    frontend:
        build: ./sveltekit_frontend
        expose:
            - "3000"
        volumes:
            - /app/node_modules # Prevent host node_modules override (optional but smart)
        depends_on:
            - backend

        develop:
            watch:
                - action: sync
                  path: ./sveltekit_frontend
                  target: /app

    backend:
        build: ./python_backend
        expose:
            - "5000"

        develop:
            watch:
                - action: sync
                  path: ./python_backend
                  target: /app

    caddy:
        image: caddy:2.10
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - caddy_data:/data
            - caddy_config:/config
        depends_on:
            - frontend
            - backend

volumes:
    caddy_data:
    caddy_config:
