/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/spotify/currently-playing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Currently Playing
         * @description Get the currently playing track from user's spotify
         */
        get: operations["currently_playing_spotify_currently_playing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spotify/last-played": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Last Played
         * @description Get the last played track from user's spotify
         */
        get: operations["last_played_spotify_last_played_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spotify/top/{type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Top Type
         * @description Get the top `type` from user's spotify
         */
        get: operations["top_type_spotify_top__type__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books/currently-reading": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Currently Reading */
        get: operations["currently_reading_books_currently_reading_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/featured": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Featured Projects */
        get: operations["featured_projects_projects_featured_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthcheck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthcheck */
        get: operations["healthcheck_healthcheck_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** FeaturedProject */
        FeaturedProject: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Year */
            year?: string | null;
            /** Status */
            status?: string | null;
            /** Tags */
            tags?: string[];
            /**
             * Href
             * Format: uri
             */
            href: string;
            /** Links */
            links?: components["schemas"]["ProjectLink"][];
            /** Accent */
            accent?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HardcoverBook */
        HardcoverBook: {
            /** Title */
            title: string;
            /** Author */
            author: string;
            /** Pages */
            pages?: number | null;
            /** Image Url */
            image_url?: string | null;
            /** Image Dominant Color */
            image_dominant_color?: string | null;
            /** Progress */
            progress?: number | null;
            /**
             * Link
             * Format: uri
             */
            link: string;
        };
        /** HardcoverErrorMessage */
        HardcoverErrorMessage: {
            /** Error */
            error: string;
            /** Message */
            message: string;
        };
        /** HealthcheckResponse */
        HealthcheckResponse: {
            /** Condition */
            condition: string;
        };
        /** ProjectLink */
        ProjectLink: {
            /** Label */
            label: string;
            /**
             * Href
             * Format: uri
             */
            href: string;
            /**
             * External
             * @default true
             */
            external: boolean;
        };
        /** SpotifyErrorMessage */
        SpotifyErrorMessage: {
            /** Error */
            error: string;
            /** Message */
            message: string;
        };
        /**
         * TopArtist
         * @description Dataclass representing an artist returned from the spotify's top artists response.
         */
        TopArtist: {
            /** Name */
            name: string;
            /**
             * Url
             * Format: uri
             */
            url: string;
            /**
             * Image
             * Format: uri
             */
            image: string;
        };
        /**
         * Track
         * @description Dataclass representing the a track returned from the spotify api.
         *
         *     Most of the data from the original response isn't included here since
         *     we're only interested in data our application actually requires.
         */
        Track: {
            /** Name */
            name: string;
            /** Artists */
            artists: string[];
            /**
             * Track Url
             * Format: uri
             */
            track_url: string;
            /** Is Playing */
            is_playing?: boolean | null;
            /** Album Name */
            album_name: string;
            /**
             * Album Image
             * Format: uri
             */
            album_image: string;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Progress Ms */
            progress_ms?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    currently_playing_spotify_currently_playing_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Track"];
                };
            };
            /** @description Nothing is currently playing on user's spotify */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The Spotify API returned an error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "SpotifyError",
                     *       "message": "Authorization with access token unsuccessful"
                     *     }
                     */
                    "application/json": components["schemas"]["SpotifyErrorMessage"];
                };
            };
        };
    };
    last_played_spotify_last_played_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Track"];
                };
            };
            /** @description No recent spotify track available */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The Spotify API returned an error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "SpotifyError",
                     *       "message": "Authorization with access token unsuccessful"
                     *     }
                     */
                    "application/json": components["schemas"]["SpotifyErrorMessage"];
                };
            };
        };
    };
    top_type_spotify_top__type__get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                type: "artists" | "tracks";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Track"][] | components["schemas"]["TopArtist"][];
                };
            };
            /** @description No top spotify data available */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description The Spotify API returned an error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "SpotifyError",
                     *       "message": "Authorization with access token unsuccessful"
                     *     }
                     */
                    "application/json": components["schemas"]["SpotifyErrorMessage"];
                };
            };
        };
    };
    currently_reading_books_currently_reading_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HardcoverBook"];
                };
            };
            /** @description No active currently-reading book */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The Hardcover API returned an error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "HardcoverError",
                     *       "message": "The upstream hardcover service returned an invalid response"
                     *     }
                     */
                    "application/json": components["schemas"]["HardcoverErrorMessage"];
                };
            };
        };
    };
    featured_projects_projects_featured_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeaturedProject"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthcheck_healthcheck_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthcheckResponse"];
                };
            };
        };
    };
}
