// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, type Options as Options2, type RequestResult, type TDataShape, urlSearchParamsBodySerializer } from './client';
import { client } from './client.gen';
import type { AdminLoginAuthData, AdminLoginAuthErrors, AdminLoginAuthResponses, AdminVerifyAuthData, AdminVerifyAuthResponses, CurrentlyPlayingSpotifyData, CurrentlyPlayingSpotifyErrors, CurrentlyPlayingSpotifyResponses, CurrentlyReadingBooksData, CurrentlyReadingBooksErrors, CurrentlyReadingBooksResponses, FeaturedProjectsData, FeaturedProjectsErrors, FeaturedProjectsResponses, GenerateViewerSessionAuthData, GenerateViewerSessionAuthResponses, HealthcheckData, HealthcheckResponses, LastPlayedSpotifyData, LastPlayedSpotifyErrors, LastPlayedSpotifyResponses, TopTypeSpotifyData, TopTypeSpotifyErrors, TopTypeSpotifyResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Currently Reading
 */
export const currentlyReadingBooks = <ThrowOnError extends boolean = false>(options?: Options<CurrentlyReadingBooksData, ThrowOnError>): RequestResult<CurrentlyReadingBooksResponses, CurrentlyReadingBooksErrors, ThrowOnError> => (options?.client ?? client).get<CurrentlyReadingBooksResponses, CurrentlyReadingBooksErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/books/currently-reading',
    ...options
});

/**
 * Featured Projects
 */
export const featuredProjects = <ThrowOnError extends boolean = false>(options?: Options<FeaturedProjectsData, ThrowOnError>): RequestResult<FeaturedProjectsResponses, FeaturedProjectsErrors, ThrowOnError> => (options?.client ?? client).get<FeaturedProjectsResponses, FeaturedProjectsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/projects/featured',
    ...options
});

/**
 * Currently Playing
 *
 * Get the currently playing track from user's spotify
 */
export const currentlyPlayingSpotify = <ThrowOnError extends boolean = false>(options?: Options<CurrentlyPlayingSpotifyData, ThrowOnError>): RequestResult<CurrentlyPlayingSpotifyResponses, CurrentlyPlayingSpotifyErrors, ThrowOnError> => (options?.client ?? client).get<CurrentlyPlayingSpotifyResponses, CurrentlyPlayingSpotifyErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/spotify/currently-playing',
    ...options
});

/**
 * Last Played
 *
 * Get the last played track from user's spotify
 */
export const lastPlayedSpotify = <ThrowOnError extends boolean = false>(options?: Options<LastPlayedSpotifyData, ThrowOnError>): RequestResult<LastPlayedSpotifyResponses, LastPlayedSpotifyErrors, ThrowOnError> => (options?.client ?? client).get<LastPlayedSpotifyResponses, LastPlayedSpotifyErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/spotify/last-played',
    ...options
});

/**
 * Top Type
 *
 * Get the top `type` from user's spotify
 */
export const topTypeSpotify = <ThrowOnError extends boolean = false>(options: Options<TopTypeSpotifyData, ThrowOnError>): RequestResult<TopTypeSpotifyResponses, TopTypeSpotifyErrors, ThrowOnError> => (options.client ?? client).get<TopTypeSpotifyResponses, TopTypeSpotifyErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/spotify/top/{type}',
    ...options
});

/**
 * Generate Viewer Session
 *
 * Endpoint called by the frontend on the visitor's first initial page load.
 * Returns a signed, stateless token valid for 30 minutes.
 */
export const generateViewerSessionAuth = <ThrowOnError extends boolean = false>(options?: Options<GenerateViewerSessionAuthData, ThrowOnError>): RequestResult<GenerateViewerSessionAuthResponses, unknown, ThrowOnError> => (options?.client ?? client).post<GenerateViewerSessionAuthResponses, unknown, ThrowOnError>({ url: '/auth/viewer-session', ...options });

/**
 * Admin Login
 *
 * Processes administrative logins via OAuth2 standard password flow.
 * Verifies credentials against Postgres and yields an elevated access token.
 */
export const adminLoginAuth = <ThrowOnError extends boolean = false>(options: Options<AdminLoginAuthData, ThrowOnError>): RequestResult<AdminLoginAuthResponses, AdminLoginAuthErrors, ThrowOnError> => (options.client ?? client).post<AdminLoginAuthResponses, AdminLoginAuthErrors, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    url: '/auth/admin-login',
    ...options,
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        ...options.headers
    }
});

/**
 * Admin Verify
 *
 * Endpoint to verify the validity of an admin token.
 * Returns the admin's username and email if valid.
 */
export const adminVerifyAuth = <ThrowOnError extends boolean = false>(options?: Options<AdminVerifyAuthData, ThrowOnError>): RequestResult<AdminVerifyAuthResponses, unknown, ThrowOnError> => (options?.client ?? client).get<AdminVerifyAuthResponses, unknown, ThrowOnError>({ url: '/auth/admin-verify', ...options });

/**
 * Healthcheck
 */
export const healthcheck = <ThrowOnError extends boolean = false>(options?: Options<HealthcheckData, ThrowOnError>): RequestResult<HealthcheckResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthcheckResponses, unknown, ThrowOnError>({ url: '/healthcheck', ...options });
