// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
	baseUrl: `${string}://${string}/api` | (string & {});
};

/**
 * Body_admin_login_auth_admin_login_post
 */
export type BodyAdminLoginAuthAdminLoginPost = {
	/**
	 * Grant Type
	 */
	grant_type?: string | null;
	/**
	 * Username
	 */
	username: string;
	/**
	 * Password
	 */
	password: string;
	/**
	 * Scope
	 */
	scope?: string;
	/**
	 * Client Id
	 */
	client_id?: string | null;
	/**
	 * Client Secret
	 */
	client_secret?: string | null;
};

/**
 * FeaturedProject
 */
export type FeaturedProject = {
	/**
	 * Name
	 */
	name: string;
	/**
	 * Description
	 */
	description: string;
	/**
	 * Year
	 */
	year?: string | null;
	/**
	 * Status
	 */
	status?: string | null;
	/**
	 * Tags
	 */
	tags?: Array<string>;
	/**
	 * Href
	 */
	href: string;
	/**
	 * Links
	 */
	links?: Array<ProjectLink>;
	/**
	 * Accent
	 */
	accent?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
	/**
	 * Detail
	 */
	detail?: Array<ValidationError>;
};

/**
 * HardcoverBook
 */
export type HardcoverBook = {
	/**
	 * Title
	 */
	title: string;
	/**
	 * Author
	 */
	author: string;
	/**
	 * Pages
	 */
	pages?: number | null;
	/**
	 * Image Url
	 */
	image_url?: string | null;
	/**
	 * Image Dominant Color
	 */
	image_dominant_color?: string | null;
	/**
	 * Progress
	 */
	progress?: number | null;
	/**
	 * Link
	 */
	link: string;
};

/**
 * HardcoverErrorMessage
 */
export type HardcoverErrorMessage = {
	/**
	 * Error
	 */
	error: string;
	/**
	 * Message
	 */
	message: string;
};

/**
 * HealthcheckResponse
 */
export type HealthcheckResponse = {
	/**
	 * Condition
	 */
	condition: string;
};

/**
 * ProjectLink
 */
export type ProjectLink = {
	/**
	 * Label
	 */
	label: string;
	/**
	 * Href
	 */
	href: string;
	/**
	 * External
	 */
	external?: boolean;
};

/**
 * SpotifyErrorMessage
 */
export type SpotifyErrorMessage = {
	/**
	 * Error
	 */
	error: string;
	/**
	 * Message
	 */
	message: string;
};

/**
 * TokenResponse
 */
export type TokenResponse = {
	/**
	 * Access Token
	 */
	access_token: string;
	/**
	 * Token Type
	 */
	token_type?: string;
};

/**
 * TopArtist
 *
 * Dataclass representing an artist returned from the spotify's top artists response.
 */
export type TopArtist = {
	/**
	 * Name
	 */
	name: string;
	/**
	 * Url
	 */
	url: string;
	/**
	 * Image
	 */
	image: string;
};

/**
 * Track
 *
 * Dataclass representing the a track returned from the spotify api.
 *
 * Most of the data from the original response isn't included here since
 * we're only interested in data our application actually requires.
 */
export type Track = {
	/**
	 * Name
	 */
	name: string;
	/**
	 * Artists
	 */
	artists: Array<string>;
	/**
	 * Track Url
	 */
	track_url: string;
	/**
	 * Is Playing
	 */
	is_playing?: boolean | null;
	/**
	 * Album Name
	 */
	album_name: string;
	/**
	 * Album Image
	 */
	album_image: string;
	/**
	 * Duration Ms
	 */
	duration_ms?: number | null;
	/**
	 * Progress Ms
	 */
	progress_ms?: number | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
	/**
	 * Location
	 */
	loc: Array<string | number>;
	/**
	 * Message
	 */
	msg: string;
	/**
	 * Error Type
	 */
	type: string;
	/**
	 * Input
	 */
	input?: unknown;
	/**
	 * Context
	 */
	ctx?: {
		[key: string]: unknown;
	};
};

export type CurrentlyReadingBooksData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/books/currently-reading';
};

export type CurrentlyReadingBooksErrors = {
	/**
	 * The Hardcover API returned an error
	 */
	502: HardcoverErrorMessage;
};

export type CurrentlyReadingBooksError =
	CurrentlyReadingBooksErrors[keyof CurrentlyReadingBooksErrors];

export type CurrentlyReadingBooksResponses = {
	/**
	 * Successful Response
	 */
	200: HardcoverBook;
	/**
	 * No active currently-reading book
	 */
	204: void;
};

export type CurrentlyReadingBooksResponse =
	CurrentlyReadingBooksResponses[keyof CurrentlyReadingBooksResponses];

export type FeaturedProjectsData = {
	body?: never;
	path?: never;
	query?: {
		/**
		 * Limit
		 */
		limit?: number;
	};
	url: '/projects/featured';
};

export type FeaturedProjectsErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type FeaturedProjectsError =
	FeaturedProjectsErrors[keyof FeaturedProjectsErrors];

export type FeaturedProjectsResponses = {
	/**
	 * Response Featured Projects Projects Featured Get
	 *
	 * Successful Response
	 */
	200: Array<FeaturedProject>;
};

export type FeaturedProjectsResponse =
	FeaturedProjectsResponses[keyof FeaturedProjectsResponses];

export type CurrentlyPlayingSpotifyData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/spotify/currently-playing';
};

export type CurrentlyPlayingSpotifyErrors = {
	/**
	 * The Spotify API returned an error
	 */
	502: SpotifyErrorMessage;
};

export type CurrentlyPlayingSpotifyError =
	CurrentlyPlayingSpotifyErrors[keyof CurrentlyPlayingSpotifyErrors];

export type CurrentlyPlayingSpotifyResponses = {
	/**
	 * Successful Response
	 */
	200: Track;
	/**
	 * Nothing is currently playing on user's spotify
	 */
	204: void;
};

export type CurrentlyPlayingSpotifyResponse =
	CurrentlyPlayingSpotifyResponses[keyof CurrentlyPlayingSpotifyResponses];

export type LastPlayedSpotifyData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/spotify/last-played';
};

export type LastPlayedSpotifyErrors = {
	/**
	 * The Spotify API returned an error
	 */
	502: SpotifyErrorMessage;
};

export type LastPlayedSpotifyError =
	LastPlayedSpotifyErrors[keyof LastPlayedSpotifyErrors];

export type LastPlayedSpotifyResponses = {
	/**
	 * Successful Response
	 */
	200: Track;
	/**
	 * No recent spotify track available
	 */
	204: void;
};

export type LastPlayedSpotifyResponse =
	LastPlayedSpotifyResponses[keyof LastPlayedSpotifyResponses];

export type TopTypeSpotifyData = {
	body?: never;
	path: {
		/**
		 * Type
		 */
		type: 'artists' | 'tracks';
	};
	query?: {
		/**
		 * Limit
		 */
		limit?: number;
	};
	url: '/spotify/top/{type}';
};

export type TopTypeSpotifyErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
	/**
	 * The Spotify API returned an error
	 */
	502: SpotifyErrorMessage;
};

export type TopTypeSpotifyError =
	TopTypeSpotifyErrors[keyof TopTypeSpotifyErrors];

export type TopTypeSpotifyResponses = {
	/**
	 * Response Top Type Spotify Top  Type  Get
	 *
	 * Successful Response
	 */
	200: Array<Track> | Array<TopArtist>;
	/**
	 * No top spotify data available
	 */
	204: void;
};

export type TopTypeSpotifyResponse =
	TopTypeSpotifyResponses[keyof TopTypeSpotifyResponses];

export type GenerateViewerSessionAuthData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/auth/viewer-session';
};

export type GenerateViewerSessionAuthResponses = {
	/**
	 * Successful Response
	 */
	200: TokenResponse;
};

export type GenerateViewerSessionAuthResponse =
	GenerateViewerSessionAuthResponses[keyof GenerateViewerSessionAuthResponses];

export type AdminLoginAuthData = {
	body: BodyAdminLoginAuthAdminLoginPost;
	path?: never;
	query?: never;
	url: '/auth/admin-login';
};

export type AdminLoginAuthErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type AdminLoginAuthError =
	AdminLoginAuthErrors[keyof AdminLoginAuthErrors];

export type AdminLoginAuthResponses = {
	/**
	 * Response Admin Login Auth Admin Login Post
	 *
	 * Successful Response
	 */
	200: {
		[key: string]: string;
	};
};

export type AdminLoginAuthResponse =
	AdminLoginAuthResponses[keyof AdminLoginAuthResponses];

export type AdminVerifyAuthData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/auth/admin-verify';
};

export type AdminVerifyAuthResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type HealthcheckData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/healthcheck';
};

export type HealthcheckResponses = {
	/**
	 * Successful Response
	 */
	200: HealthcheckResponse;
};

export type HealthcheckResponse2 =
	HealthcheckResponses[keyof HealthcheckResponses];
