[spotify]

baseUrl = "http://localhost:8000/spotify/"
currentlyPlayingUrl = "currently-playing"
lastPlayedUrl = "last-played"

[spotify.topItems]
limit = 10
artistsUrl = "top-artists"
tracksUrl = "top-tracks"

[location]
baseUrl = "http://localhost:8000/location"
currentLocationUrl = "/current-location-img"
